require("plugins.plugins")
require("plugins.configs.nvimtree")
require("plugins.configs.coc")
require("plugins.configs.bufferline")
require("plugins.configs.telescope")
require("plugins.configs.diffview")
require("colorschemes.cyberdream")
require("gwondori")
